# Generated by Django 4.2.7 on 2026-04-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
                ('backdrop_path', models.CharField(blank=True, max_length=300)),
                ('trailer_key', models.CharField(blank=True, max_length=50)),
                ('actors', models.TextField(blank=True)),
                ('directors', models.TextField(blank=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='films', to='films.genre')),
            ],
        ),
    ]
